repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yaml"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.9.0
    hooks:
      - id: yamlfmt
        exclude: '(^|/).*\\.sops\\.yaml$'
  - repo: local
    hooks:
      - id: validate-kustomize
        name: Validate kustomize build + kubeconform
        entry: scripts/validate.sh
        language: system
        pass_filenames: false
