apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
  - cert-manager-cloudflare-secret.sops.yaml
  - cert-manager-clusterissuer.yaml
  - romanpeters-wildcard-cert.yaml
  - cilium-helmrepo.yaml
  - cilium-helmrelease.yaml
  - cilium-lbippool.yaml
  - cilium-l2announcementpolicy.yaml
  - external-dns-namespace.yaml
  - external-dns-rbac.yaml
  - external-dns.sops.yaml
  - external-dns-deployment.yaml
  - external-dns-resourcequota.yaml
  - external-dns-limitrange.yaml
  - trivy-operator-namespace.yaml
  - trivy-operator-helmrepo.yaml
  - trivy-operator-helmrelease.yaml
  - trivy-system-resourcequota.yaml
  - trivy-system-limitrange.yaml
  - traefik-helmchartconfig.yaml
  - traefik-dashboard-ingressroute.yaml
  - traefik-internal-service.yaml
  - traefik-tlsstore.yaml
