apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-vips
  namespace: metallb-system
spec:
  addresses:
    - 10.10.20.240-10.10.20.241
    - fd7b:c87:127b:14::240-fd7b:c87:127b:14::241
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan-vips
  namespace: metallb-system
spec:
  ipAddressPools:
    - lan-vips
