apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  annotations:
    lbipam.cilium.io/ips: 10.10.20.241
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  ports:
    - name: websecure-int
      port: 443
      targetPort: websecure-int
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
