apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
spec:
  type: LoadBalancer
  loadBalancerClass: metallb.universe.tf/metallb
  loadBalancerIP: 10.10.20.241
  ports:
    - name: websecure-int
      port: 443
      targetPort: websecure-int
      protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
