apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/instance: default-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  defaultCertificate:
    secretName: romanpeters-nl-tls
