apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager-config
    app.kubernetes.io/instance: alertmanager-config-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:PF8/FQH/0ruu2tn8hlEXDM3upSVaNUWKh9MdApuJckucZhBp69/FIqhx9bYg/Ep0xj/N4RkIorHFz/5VJpilqCMdTZrRtUEoowfYiqCeJZQEkxRvSQJiXCCLtCL9ilxWenyiMQfiUE/rkULp9N4UfjAYFxdARAgKVvqVGfaykiDmEOf8Iwxt0bS4u82Rbl4JSPpE3yNc+6m2/LBInkUrBqGHSHLkW7PsAApU6ME4piXI5x4t1rGuEPP4HMuxq485UELB4nOb9OiKLTGuXMf5Ph+b98bWdv4pqzKPSJawdLb+e/ZovasgSNx9vRV/fCsA6yvxp402wxFqpkZucxAmOvistjnfeWQYxmWObHMfcf4vkmrQYXqM6vxkWG/iilexh6y7AEtULM8iUHKxIKlhiHVXsSx9SH6q2891fLJLe2t8fEsbLo929lOTC5GlPjLzj4E9SArw9OqqV6O2ky3YuxuYn/gJx6vjLGgBukPE504Q0rI/Ijs4a5d4VwnAbuvLIvKOzrXLEFd/QcxiAUwgTj7Fvg4CI1J1skdRZpAHiYi3Mj9wrWcNs8UmEq1OP177++fQNWV8lI1uRiQa9uKMBJ6KN/N75LAQzb2fyw/IsJv1SmsYaDDdiZTeVQU+pnlqnHFLvBkq73Nd6Dfl2XF66NJPXv7TKk37WZwrcIhkDbFp4Sit5u9tTLi50r28re2X6VG0YIcHBBDiqbSRZb0aNYWjuXirEKAprXO/3ZI+bVIAcXajNS+NblM3CX5MnfoLS4hdUd675d6GWaR8byQk2sj2xb4/ZK+bM85Zb37ONEJslpQDPE9EWLUssbvXxxb6dM8ZQgyi/sRuavXD7TtcGvLePWWNZObRfgbnA43kpce1KcLE/h+xaaN0DdYVfst2hmk/XKQPvpG1PdVQ6/V8uVDCcxVz7dfnDkxxEPzhthMeSxyLDsm992ZWC6TXiGpDJVgu9cuvXkMiOXsY4x0jqU2CgdWvBGJJe0M5Ddx3VFo9YYOYIuKloOSwNgB5VDSj5ln5xeKLNa3wRx6X4jneSgOF3bNhuUXcbKSIkrz20Uqp+QtYKooQ1P+ybXeASF8/UktJltHZ76DpQC1t4pJ51XLu8PCR8OZ/gjIwD67Rn8LgN61kDfntR9/seh0teRnqFyq1ghdbd28NIsZWuNLxCla5EdLSz8t4/bnpRO5EvHfwQkk=,iv:eaCO9SMuI97tcBDjbxrwTQwpeJc4rWAkS7eHM1NEebE=,tag:HK3hiY4VQgknOBqIrmuVrQ==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SzN3OXNFV2lYRVQwVURq
        eWxCOGJ2U2xnM29FZ3lqN1lvZXl3Z2hUSlIwCklGZDFKOWgxZ3JLeWZNTHVJUEtk
        c3ptQW5waTQxcHZJT0Q1R1ZyaHVKbG8KLS0tIERyTzJoRHZsM01IOU9rUUlpNXJI
        Z045ZXMzY0NQTGJ2UHlvSGRpdlhCQk0K4yOyEL44zywBFD6iOVfE6OSqzJx2ziPe
        w0Vhw64qoOOzJBhDzx9eD/vIHiDFgxM4MY8ciQjvMZkRw0MD+kX/fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T18:35:06Z"
  mac: ENC[AES256_GCM,data:4cMVIAuhSqTLU/njq0+q17fg2rTSLXWR8KFBmgQuKxwGG16UmReR+W7uiCUKOzvcbAPARcgQB7NzRztayJMw1EG/9LC4gimTVgmgbqNuQbSOOHu3OFWTuOWFwBpNzuz5xVM0QIJRX8MhUK++MJPb+ClmutIzE8CCDfiRO2CF/Eo=,iv:Eg6DyEE9Cl4LSA4bXfKqPZd0Neyh9m1M6KcQViavo54=,tag:sMCxo9lRRpmah0FvtPkyGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
