apiVersion: ENC[AES256_GCM,data:dB0=,iv:fpIJz1XodHc3irx6oMYbMnkWNY0cHRA1Svg9vTGjhoo=,tag:NevbMoM3yVQXMGiSaM6Jog==,type:str]
kind: ENC[AES256_GCM,data:qJolgCZs,iv:Ej0bA5URSbw6a42uicmgnrwzIaub6LJ7B6wFx328uHI=,tag:sBMf6AR39yAxDgyr3HjfJw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:qqhG1clgIHj5FthYLjZxxrnFpg==,iv:QZRWH3U69Wsjl1OZ9ZlKTR5YrmUdDSUfhLpNskSGN/Y=,tag:TccxnusiA6siKKwTuQdQaA==,type:str]
  namespace: ENC[AES256_GCM,data:LpJTyIEIDgUz8w==,iv:o/62X9HPCSiE8fsljkDTjswjz46Xtug7xvw8b1cnVSE=,tag:ZyXr2OuvEdjM12lrCAgujw==,type:str]
type: ENC[AES256_GCM,data:MOYUADbs,iv:oEWIsiSP+JPu1TxexgVZbwwiJkIT58JCDy9eYkRj2+4=,tag:A7WkpiLelDAygGO0GwvKbw==,type:str]
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:5TM8iD5fpMoTngJ+9bP/e00ahgo6rfT+nib6DXzDO2upOO2eOQbITyjmnZXqeeFB99ihrdX3R4P3XJNeV1RJlptZ5D098p9FcAoXNq5gvcL0xZjm9wN3eZviX8PXCl8pahE9RSdE1Ei3qE5m1nu79kICDX/yIqkk6fd+B54B1vUH7LUMTUwkXYKLqZGg1XbUcaScEGV1Ep2jxq9Rjl/hdtsDip7pzFVVpCX3KLsIdgMsZHlmPKYiY1asxjXuspxWD7hBPnRCZ3rlWJwWe61BcJsThULhMXLVWZE4gnDBEIl3e/G57CSedTAuzBLmb9WbPozePGeHsXO7bBBBxGxmDl59Lf8ZcIaAXwUZ0wixdpecYa1Kp2aBz9phazVkW8+0vQBRFyPcQSN/Qtl6O0Bnx6sUhleN7zoxASMIioqs4Ch0mo5asQBaN5HvCKORxAYB2mL1TkayVQtCfq5w7YeeqWoTfuqS2mwPRj7OQ2QaZRUYr5yVRKL/PdEF6bYD4uBWUuES5QUO+kT6hYLDcGsP+GcjZzgEZoY/laMLJZ26kk/hxv6sa+h742fnMTIrRDaf+a0B7F7q0VAFCGyiGCOAKVo3PbfYoJ6s75UQ3oFx0b3S1JPB7+qYoGLfN2juiZl0z5+3eeFcOixuZ1tJNHXsYEE=,iv:km9D/w2+6NoZrjhjk2YGpzHkq82LIdZiox1Ktqnaf8A=,tag:GlLhiTxVnsxC6hnxO2EQUA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTHZIdDMvWWQvSVUrTloz
        TEl2b2pXZjhXNnF5NDJ6d2p6NTEyTzZlVmhvCkxYZVR2d20yZmRhbU5vYmRsYk9U
        cWpHd0V1Q2FpSURlK29RY0srQUdYWmcKLS0tIGxMRXBmZktFWTJISERSTHgrdE5O
        ZllBa2JZbFBoNjQ3d0VlOFlhak1QWlEKMmKZBclgOzjQMo0fcya2EdE7yiTyHqJP
        1cumfRu121hqx+E7q9zKbpGRIBMAxRqGrMfrh8drhR8cLienL84ZIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T20:30:19Z"
  mac: ENC[AES256_GCM,data:ZGxrUrm1/tFmAnH+VK0ckYsrAULrM4i1r8XnNfqJbS/QDa6UoT/xLSbs+uOr4TLmWoNs6JhHTQ03S5ccHlM6KOOr5UwnP8xVWW90URJv55Pk46DIx6k7IuVVAv5S/y4LibbwGPr4em+IbJeVzB5GlTW9eJslL3x/qtI1H8bhL9M=,iv:XV6SgI6kEmembvlhQVYELlB0wbkuJx6hqQoSRYQaqU4=,tag:Ae5ZiddshDVGwgvON1Ss+Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
