apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:eynrOmd19ecgkJunYofw7+y1ZdMzsVlMI3L1ZYgQVo+A6KJyZkh52Z+2xAJ1+GcjWvrQzOfdpkfwRUZLD7OgdUV7Hcle0e4R9U0V0Tjs4GSEPLRg1cfcjx2DLpDERGCwiAmFJvGoM47lajRDQL8EoQSLqEnX8In+kAoVzwgIDVq21iAh53adFyPSnd0uzhF71ULcmXZPDYLynk7jSwCTVyr74Wgbxj7oKsKJx4CSe8Sg+vLvPyI55TfHQ88O1UgcdKrLlnuWNh6ZAL0oYF7dcl7GQJW/qy0g3jm1G9qOI4343AK4G3PjHkDitsLP1OPyFJQh4DBqylZpLDVWeLEM7/3jxLyfigpVTo1lhGUYd2uK5Di6eo0HCPcXsFrXrP++wSQ6PC6rbyIMF2A/NqpJV6qftIXo9ueV3kUpoZ3WNpYEv9zk3Tx9moASuZ1U5T+DbxB8KPeVvjkDvc74tcLxUCpknqitQaGjTMFaEIa6CTl3Xbaa19jv/4GE43yAwt8Fz7824ZzUIPC6xlsQuqYAM+1q4LOE4sGhykA22c3t5dm6oIGLnaiJYH0CJpdO0f4kAO+ZOx3pBrLafhcXoCWm86o9ZcmPlNXqFPxko34Gnm2jEOqIPzzHaTXJsS9xtDPCXRnemo/wagInxUXuwl+6Yw9cG7DQmO3QQ4iq684b9NToqw3s48wj/3Wm9iUmGnyKKf5VjZkFwUSC/8+p3soH3HZnXoFeRJsDmlhXGjF3c4CPPXIyYLm3TclFB7CEgH4YhdDj/ZSG8f5LHvI8c0P643auUpbVpgjTmV29cVRtkNVkLeGBb1riwaLk8jA/p1bUWPWrmIu5WOXf5Va76joCmjCWW8nmF+fOkkzECGlm5+oG6yr48iiv0FPU6+oIG8/2/7Dn9bGyDy6Uqrqb7A05soviCMDgRw1MsKNQDRmCEehT1mRONws8XX1QwlfynYXTDS8e3Q1nUGD/KDFYB9CuR5oy8uD613oBeNc1uqcMmt+os1CsuR/+YhFYQiOBRE/KYcR5Af2/B/e5sqHaXlsghTXmGnUOE0rAYNxniwXpQDsiKFW/uHuxp3iZpfkP02JAllrNpcLHPKQqIoUE0rU2N2qbaCK/hnT/9qh2i/wNIJ0m0Y3B+DJRtEstH2dW9qg0Rfqbr8RSQ4+TwD9xZeWrfK+bM5p+d1/svK+GhPJ7WsNWDXs=,iv:tzmMhZ14inKyMBHFk23Y5/jVdcR9Y0dADIolrUSL9FU=,tag:N9iF+jmgfRaktN8t4u/Ekg==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQjR5dmx6cXdJUCtpT1JS
        SDdxMS8xUldGcVJiMFZIZENSaDBzT3VibFQ0CmkvbHFVNUQ5cytrWm9qTHNCSGo4
        ZlAvcXdXRnpMWmo5RkxpQUhGSm4rZ00KLS0tIGlBUzExMVRwZ29CL0puOHNTT3dL
        ZllHTE9qRFBnY0xPdjhPRG5YbDFqeVEKis8US5rHJlWq1cE5qUOZ/CRUddf12+51
        KQJ9k9sDgd6NDmO6ZAg8WDjwGRnGW0rMQiQDOIHEkG2nAEHoCFqZHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:06:31Z"
  mac: ENC[AES256_GCM,data:jamWsp9PkZcR9FlulW0ib7/m9UQLhfNn1qHk/Yc7hAlEU2mM0gxc7m8Eg1L+WRs3s8NRC4mZXMTWnhIyQiNfzz/9ix/vh/KNZcKv9b9QV1v1CEiKXPDJXsBpNtUGTvVCGWEM4mqmOPFsFXn3/MUVL5edtGtClVbpL6gJameZqBQ=,iv:zKoGFAC0c0KECFefVC06xVe6oap70rgvN4lWROcJbdc=,tag:LhzcOeUCySfD0bgMKF/2KQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
