apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:LavyteYi65I9ZX9BBqTHIHbvaCIBqewY0J8VoI4GmPJ44Os7n7msakocmuzm5ZKg5N7A/Fl6OVL8HeIfOTHBx6L4TR4EkKnH4Gea8IuITfO4QqulR8ywQWJDf2zR171K85sdvkcCRRtjxE70Ht1q9/o6vZf7itIgVB6elMFddhDvdj9qIGPlVmNmFoPYEU5tXp7jF0kmNcV0Z0x/B1eTS67z/41zyM18IzQihT/USeOaStAYssxIh1Cdmyng5yy1Iw+y5WTMpBa65xBWOA+SNp7+jFvtvO0/rivXv8hd0wGgFu4JHpfGmj6jBKMLDpNe1z4XSD43czjHgNatzhgk/LyifGo1SLhKW22zZuMYXyTSQW0HHPbwnXJwyS8basNTHEolMVNPBHxfRVP7buN6eQNXvQ4=,iv:t0UUPQJbuIG5DL7dhx2pOY6h8aQQwSIwqZ42qwmue44=,tag:gwqEOY4YVhdZ/v+BxlghZg==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUXVNNFhGVG5vcHJuN2lp
        QVFiMEFtZ1VveEdMUXkvL2FFMVpWSGlRNTJFCldZdVRLOHlhWUtaUDVab3dUc0cy
        VE1pd254SkZXeGErdkV2dDVFQytCTU0KLS0tIEdER1hUUEl1MTZIeXlzeUtTSlhj
        Z0RnejE5RjZQZFJEckVCalBsajlxK2sKWIuj3TuslAtDQpNjCaMYcbW9lD8PAzcg
        afG9Ji63P+1OoO3kBP5OdU5l5FaPY/ZfMtcsPbb6giG3Rl7QS8vqNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T22:14:06Z"
  mac: ENC[AES256_GCM,data:OwcWvRCpGTceYx7lIqyG8HA3DiMUDvGom1912D+BkybfggRWPwaieAoLU0/dLWOSEYUmzK0cctWElzoaXpwB529OIDEfrTNGQYQCSKh25R0JMch2KicozzIyjSIs0YhvlG4Uzv60FGyT3m29naUs7nvjELeswXvItmr9vTyu5us=,iv:jnVCb40a30p59tWfprdx3aBuXDf28DkNqNPG90dZPJQ=,tag:0RS2Dr5uXnYG8x8+AXMLpw==,type:str]
  encrypted_regex: ^(stringData)$
  version: 3.11.0
