apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:vPqHeBzk0R0DPvvo4UVpzsXZVzENcJV0sEmx3zWSSSjoiY49heXzP2Cp6IH9ZjMd7fXukTOtShNYDW8OzmPnaWuyRGzvmFHGX2t5eHcSdR+XKJkOQUzGHr/d9BUYmcKfK3GDGVmAA7fYaKm6hk29FOJ5HwtuCLn1Wd9HMMcI0xIao8JNLDoF12SirQPZQAbIpXeBB1ZICDia9kYFpplYZ+pIx5CmA16yP72t5bJzT1NlOgHTGbYfxt+8FVhSqy+XGg3/M/ja3yCRhv2uFAypRbL/m9F5HdhVA4V0nRKLdmQaqsg8OVjrMENVo+odK2PVnMYfUacQgnPzxNvLoP1vXQRyS/PT4xG76n7ElE1LRnPTUr/RG1Z4KR31uUP6rs9LhRxibNlrco7rqS3qJTjaap8m2Ztwelp/T3iI93RB6Am4j43WRO/B3rcE3Xj0DNvTgRd9V5bt6VlLJuiyPVB9G9WK0ZrY1gtxKLYMJH7EfaDVAUJyQ5YGp0ysNY/vo8GFLc9bh1vCcS3OvqmLRitirGwgKAWRi3t3RXSMmyyFZHPhiIBmlIZsEyf5W0IvCVUqnXTOtbQ7ekjIWu5WRpkeTfYH4TU2slsDOuwf2QmivqLMO4LaQ1V/BXgfjtQBIYii5RGgVckvgwwVgN168S7TGTs=,iv:dUvhvdU9rxC793vbbIrJIr41p3mrbpgSAINAbS1kbVw=,tag:MtxU+r7KeQiaT2WapWCAKA==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZGpBS0lnei9rTk5lV2JY
        Q0o1QUpRcnhLMExMeFlkNmEwNHdiZDVtdm5NCldGQkduM3owZ3ZWQUlxWHlDM1g3
        NkQvY0swem1GSytEajhUVHR2NXlWaWcKLS0tIEFIZVVWb0daTndpQUp6LzliaDZ6
        dXdxYjZFRkVhdkM5UHNzNysySkpwQncKvEmI7uhuoL58CpcOvYwTnczh6LUTDHsW
        QwS9a9/9hanQyt+HWMCHwqZSw2MGh4+uX6tjUxPuEjHPExagj0qgYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T20:34:49Z"
  mac: ENC[AES256_GCM,data:oLLDJYGHCnYItzLoIy9u5Axx75HDNCc+TP5HtdZbWlNKwGmSrlWLOW3SGJzKA1Hluj+OWH5yeheXCO2ctIPNygRWXejh2DgW6U42YlGyNoxkJHf9DcNz7lMEExcP8byKM0MANU1MkwtCuQbdvx+OSRLrx18z4NJIw0yI6GBjyGI=,iv:f2WDucj2wqyvNcstTXU7il1xxaN/ZgqOXLjXdhG4NH8=,tag:k8lGnUXzj9RceCiUTYDBiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
