apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.25.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/blackbox/blackbox.yml"
          ports:
            - name: http
              containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
