apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/instance: blackbox-exporter-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.28.0@sha256:e753ff9f3fc458d02cca5eddab5a77e1c175eee484a8925ac7d524f04366c2fc
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/blackbox/blackbox.yml"
          ports:
            - name: http
              containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
