apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  labels:
    app.kubernetes.io/name: changedetection
    app.kubernetes.io/instance: changedetection-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: changedetection
  template:
    metadata:
      labels:
        app.kubernetes.io/name: changedetection
    spec:
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:0.53.5@sha256:35f9523c2a78ebea6c8cdb93ac6f16911dfd2a9e4e4d899ba40421f67191f302
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: BASE_URL
              value: "https://change.romanpeters.nl"
            - name: PLAYWRIGHT_DRIVER_URL
              value: "ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true"
          volumeMounts:
            - name: data
              mountPath: /datastore
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: changedetection-data
