apiVersion: apps/v1
kind: Deployment
metadata:
  name: glances
  namespace: monitoring
  labels:
    app.kubernetes.io/name: glances
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glances
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glances
    spec:
      containers:
        - name: glances
          image: nicolargo/glances:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-w"
          ports:
            - name: http
              containerPort: 61208
          env:
            - name: TZ
              value: "Europe/Amsterdam"
