apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glances
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
spec:
  ingressClassName: traefik
  rules:
    - host: glances.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glances
                port:
                  name: http
