apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-redirect
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-redirect
    app.kubernetes.io/instance: grafana-redirect-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  redirectRegex:
    regex: ^https?://grafana\.romanpeters\.nl/(.*)
    replacement: https://dashboard.romanpeters.nl/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  ingressClassName: traefik
  rules:
    - host: dashboard.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-redirect
  namespace: monitoring
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-grafana-redirect@kubernetescrd
  labels:
    app.kubernetes.io/name: grafana-redirect
    app.kubernetes.io/instance: grafana-redirect-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
