apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.3.3@sha256:9e1e77ade304069aee3196e9a4f210830e96e80ce9a2640891eccc324b152faf
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: GF_SERVER_ROOT_URL
              value: "https://dashboard.romanpeters.nl"
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "authentik"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana-oauth
                  key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-oauth
                  key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: "openid profile email"
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: "https://auth.romanpeters.nl/application/o/authorize/"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "https://auth.romanpeters.nl/application/o/token/"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "https://auth.romanpeters.nl/application/o/userinfo/"
            - name: GF_AUTH_SIGNOUT_REDIRECT_URL
              value: "https://auth.romanpeters.nl/application/o/grafana/end-session/"
            - name: GF_AUTH_OAUTH_AUTO_LOGIN
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              value: "contains(groups[*], 'grafana-admins') && 'Admin' || contains(groups[*], 'grafana-editors') && 'Editor' || 'Viewer'"
            - name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
              value: "preferred_username"
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_DATE_FORMATS_FULL_DATE
              value: "DD-MM-YYYY HH:mm"
            - name: GF_DATE_FORMATS_INTERVAL_SECOND
              value: "HH:mm:ss"
            - name: GF_DATE_FORMATS_INTERVAL_MINUTE
              value: "HH:mm"
            - name: GF_DATE_FORMATS_INTERVAL_HOUR
              value: "DD-MM HH:mm"
            - name: GF_DATE_FORMATS_INTERVAL_DAY
              value: "DD-MM-YYYY"
            - name: GF_DATE_FORMATS_INTERVAL_MONTH
              value: "MM-YYYY"
            - name: GF_DATE_FORMATS_INTERVAL_YEAR
              value: "YYYY"
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: datasources
          configMap:
            name: grafana-datasource-prometheus
