apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: karma-redirect
  namespace: monitoring
spec:
  redirectRegex:
    regex: ^https?://alert\.romanpeters\.nl/(.*)
    replacement: https://alerts.romanpeters.nl/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-authentik-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: alerts.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karma
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma-redirect
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-karma-redirect@kubernetescrd,infrastructure-authentik-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: alert.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karma
                port:
                  name: http
