apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: karma-redirect
  namespace: monitoring
  labels:
    app.kubernetes.io/name: karma-redirect
    app.kubernetes.io/instance: karma-redirect-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  redirectRegex:
    regex: ^https?://alert\.romanpeters\.nl/(.*)
    replacement: https://alerts.romanpeters.nl/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
  labels:
    app.kubernetes.io/name: karma
    app.kubernetes.io/instance: karma-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  ingressClassName: traefik
  rules:
    - host: alerts.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karma
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma-redirect
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-karma-redirect@kubernetescrd
  labels:
    app.kubernetes.io/name: karma-redirect
    app.kubernetes.io/instance: karma-redirect-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  ingressClassName: traefik
  rules:
    - host: alert.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karma
                port:
                  name: http
