apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - default-serviceaccount.yaml
  - config-pvcs.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml
  - alertmanager.sops.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - alertmanager-ntfy-relay-configmap.yaml
  - alertmanager-ntfy-relay-deployment.yaml
  - alertmanager-ntfy-relay-service.yaml
  - kube-state-metrics.yaml
  - kube-event-exporter.yaml
  - blackbox-exporter-configmap.yaml
  - blackbox-exporter-deployment.yaml
  - blackbox-exporter-service.yaml
  - tautulli-exporter.sops.yaml
  - tautulli-exporter-deployment.yaml
  - tautulli-exporter-service.yaml
  - tautulli-library-exporter-configmap.yaml
  - tautulli-library-exporter-deployment.yaml
  - tautulli-library-exporter-service.yaml
  - grafana-admin.sops.yaml
  - grafana-oauth.sops.yaml
  - grafana-deployment.yaml
  - grafana-datasource-prometheus.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml
  - changedetection-deployment.yaml
  - changedetection-service.yaml
  - changedetection-ingress.yaml
  - playwright-chrome-deployment.yaml
  - playwright-chrome-service.yaml
  - uptime-kuma-deployment.yaml
  - uptime-kuma-service.yaml
  - uptime-kuma-ingress.yaml
  - karma-deployment.yaml
  - karma-service.yaml
  - karma-ingress.yaml
  - ntfy-deployment.yaml
  - ntfy-service.yaml
  - ntfy-ingress.yaml
  - ntfy.sops.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
