apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v2.16.0
          imagePullPolicy: IfNotPresent
          args:
            - serve
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: NTFY_BASE_URL
              value: https://ntfy.romanpeters.nl
            - name: NTFY_BEHIND_PROXY
              value: "true"
            - name: NTFY_CACHE_FILE
              value: /var/cache/ntfy/cache.db
            - name: NTFY_AUTH
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: NTFY_AUTH
            - name: NTFY_AUTH_DEFAULT_ACCESS
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: NTFY_AUTH_DEFAULT_ACCESS
            - name: NTFY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: NTFY_USER_NAME
            - name: NTFY_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: NTFY_USER_PASS
            - name: NTFY_AUTH_FILE
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: NTFY_AUTH_FILE
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/cache/ntfy
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ntfy-data
