apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-library-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tautulli-library-exporter
    app.kubernetes.io/instance: tautulli-library-exporter-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli-library-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli-library-exporter
    spec:
      containers:
        - name: tautulli-library-exporter
          image: python:3.14-alpine@sha256:faee120f7885a06fcc9677922331391fa690d911c020abb9e8025ff3d908e510
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/exporter.py"]
          ports:
            - name: http
              containerPort: 9101
          env:
            - name: TAUTULLI_URL
              value: "https://tautulli.romanpeters.nl"
            - name: TAUTULLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tautulli-exporter
                  key: TAUTULLI_API_KEY
            - name: TAUTULLI_VERIFY_SSL
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /app/exporter.py
              subPath: exporter.py
      volumes:
        - name: config
          configMap:
            name: tautulli-library-exporter
