apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tautulli-exporter
    app.kubernetes.io/instance: tautulli-exporter-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli-exporter
    spec:
      containers:
        - name: tautulli-exporter
          image: mm404/tautulli-exporter:20260207-5f32658@sha256:10418b2ada0521f44a3b4a4b99956a4b8a1e165a8e8a93890f2b5a1316ae767f
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: TAUTULLI_URL
              value: "http://tautulli.media.svc.cluster.local:8181"
            - name: TAUTULLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tautulli-exporter
                  key: TAUTULLI_API_KEY
