apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-ext
spec:
  ingressClassName: traefik
  rules:
    - host: uptime.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
