apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: calibreweb-xscheme
  namespace: media
  labels:
    app.kubernetes.io/name: calibreweb-xscheme
    app.kubernetes.io/instance: calibreweb-xscheme-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  headers:
    customRequestHeaders:
      X-Scheme: "https"
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
  namespace: media
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
    traefik.ingress.kubernetes.io/router.middlewares: media-calibreweb-xscheme@kubernetescrd
  labels:
    app.kubernetes.io/name: calibre-web
    app.kubernetes.io/instance: calibre-web-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  ingressClassName: traefik
  rules:
    - host: ebooks.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  name: http
