apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  labels:
    app.kubernetes.io/name: cleanuparr
    app.kubernetes.io/instance: cleanuparr-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cleanuparr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cleanuparr
    spec:
      containers:
        - name: cleanuparr
          image: ghcr.io/cleanuparr/cleanuparr:2.6.4@sha256:025010f9f3f58b8bdbcdf4c5e577cd1697c5938bf29722659aac8f52033c375a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 11011
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/New_York"
            - name: PORT
              value: "11011"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cleanuparr-config
