apiVersion: v1
kind: Secret
metadata:
  name: configarr-secrets
  namespace: media
  labels:
    app.kubernetes.io/name: configarr-secrets
    app.kubernetes.io/instance: configarr-secrets-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
type: Opaque
stringData:
  secrets.yml: ENC[AES256_GCM,data:qqwc4c9Lp3ENjX88hEw6sttdgExoz/nDlC/sxlLme7dpoDrnHyyG1iez/yv4VGGKPJoBhmEdkQlLpbS2SdmeXMWShRsY0ifjnLhiZD7JpRnYyvnGXZYykzlkh1j3LKVrzTS2JFsz,iv:5n/rYjKNxCtAhKVz5NXgGarEgRLEzVntTT6X6RO5j5c=,tag:clY34UGOYC/iI+U9/IZdYg==,type:str]
sops:
  age:
    - recipient: age1txdhl8zae9a6kh6ggxydmrtstueysr32dd9fchlrp9x7n3ywhd7qzrn4k4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFRwSWM5OUNZWVF4UU5t
        ay9WdXE3VWw1aDRnZ0ZPRURPMjh4UXpOc0dVCktmNVlKQXI2RVJCQ3I4MnA0UTk1
        cDhmL0c4WjZVd0JIMmFxMkR5ZTlvMlUKLS0tIHp3SVAyUXRDWWVBbDY0TXZucVRN
        MkJGWG1YcUZjT2hMQ0NhekNMN3puLzgKHhF3qJziGixjoUoMA5c/1cp8UVRsTqll
        iENKE0/EMAsL6ft18cHZCfBSo+yFgLytkFg4m0gScf8YMKZqkKc+pA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:32:00Z"
  mac: ENC[AES256_GCM,data:o9JKBuUsJdmdWwI8F7Fbeci8e3A4rn3Wyl4fBnRxRsUC1bj6s1qLf7tru+WzetsWNHHw0FAtNJTEaFC1VHRaN2yZkK+aTrlpGywE14voKLlFcR8xSOB6YoF2oQhTGuTMCEIbwKQ/K6XbzDuW7eMPbK2tD7b4gA1pvJZV3Ee1Sbk=,iv:IzgNjoK3gi/dg6eQDKlRg+QaAjzJEAOpsPcfQV9zyBM=,tag:cjQrZuVzNFeOseepO/IQMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
