apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
  namespace: media
  labels:
    app.kubernetes.io/name: configarr
    app.kubernetes.io/instance: configarr-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY
        quality_definition:
          qualities:
            - quality: "Bluray-1080p"
              min: 50.4
              preferred: 50.4
              max: 68.3
            - quality: "Bluray-1080p Remux"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "Bluray-2160p"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "Bluray-2160p Remux"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "Bluray-480p"
              min: 2
              preferred: 2
              max: 18
            - quality: "Bluray-576p"
              min: 2
              preferred: 2
              max: 18
            - quality: "Bluray-720p"
              min: 17.1
              preferred: 17.1
              max: 68.3
            - quality: "DVD"
              min: 0
              preferred: 0
              max: 18
            - quality: "HDTV-1080p"
              min: 15
              preferred: 15
              max: 68.3
            - quality: "HDTV-2160p"
              min: 25
              preferred: 25
              max: 68.3
            - quality: "HDTV-720p"
              min: 10
              preferred: 10
              max: 68.3
            - quality: "Raw-HD"
              min: 0
              preferred: 0
              max: 35
            - quality: "SDTV"
              min: 0
              preferred: 0
              max: 18
            - quality: "Unknown"
              min: 0
              preferred: 0
              max: 18
            - quality: "WEBDL-1080p"
              min: 15
              preferred: 15
              max: 68.3
            - quality: "WEBDL-2160p"
              min: 25
              preferred: 25
              max: 68.3
            - quality: "WEBDL-480p"
              min: 0
              preferred: 0
              max: 18
            - quality: "WEBDL-720p"
              min: 10
              preferred: 10
              max: 68.3
            - quality: "WEBRip-1080p"
              min: 15
              preferred: 15
              max: 68.3
            - quality: "WEBRip-2160p"
              min: 25
              preferred: 25
              max: 68.3
            - quality: "WEBRip-480p"
              min: 2
              preferred: 2
              max: 18
            - quality: "WEBRip-720p"
              min: 10
              preferred: 10
              max: 68.3
        include:
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p
        custom_formats: []

    radarr:
      movies:
        base_url: http://radarr:7878
        api_key: !secret RADARR_API_KEY
        quality_definition:
          qualities:
            - quality: "Bluray-1080p"
              min: 50.8
              preferred: 50.8
              max: 68.3
            - quality: "Bluray-2160p"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "Bluray-480p"
              min: 0
              preferred: 0
              max: 18
            - quality: "Bluray-576p"
              min: 0
              preferred: 0
              max: 18
            - quality: "Bluray-720p"
              min: 25.7
              preferred: 25.7
              max: 68.3
            - quality: "BR-DISK"
              min: 0
              preferred: 0
              max: 35
            - quality: "CAM"
              min: 0
              preferred: 0
              max: 18
            - quality: "DVD"
              min: 0
              preferred: 0
              max: 18
            - quality: "DVD-R"
              min: 0
              preferred: 0
              max: 18
            - quality: "DVDSCR"
              min: 0
              preferred: 0
              max: 18
            - quality: "HDTV-1080p"
              min: 33.8
              preferred: 33.8
              max: 68.3
            - quality: "HDTV-2160p"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "HDTV-720p"
              min: 17.1
              preferred: 17.1
              max: 68.3
            - quality: "Raw-HD"
              min: 0
              preferred: 0
              max: 35
            - quality: "REGIONAL"
              min: 0
              preferred: 0
              max: 18
            - quality: "Remux-1080p"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "Remux-2160p"
              min: 68.3
              preferred: 68.3
              max: 68.3
            - quality: "SDTV"
              min: 0
              preferred: 0
              max: 18
            - quality: "TELECINE"
              min: 0
              preferred: 0
              max: 18
            - quality: "TELESYNC"
              min: 0
              preferred: 0
              max: 18
            - quality: "Unknown"
              min: 0
              preferred: 0
              max: 18
            - quality: "WEBDL-1080p"
              min: 12.5
              preferred: 12.5
              max: 68.3
            - quality: "WEBDL-2160p"
              min: 34.5
              preferred: 34.5
              max: 68.3
            - quality: "WEBDL-480p"
              min: 0
              preferred: 0
              max: 18
            - quality: "WEBDL-720p"
              min: 12.5
              preferred: 12.5
              max: 68.3
            - quality: "WEBRip-1080p"
              min: 12.5
              preferred: 12.5
              max: 68.3
            - quality: "WEBRip-2160p"
              min: 34.5
              preferred: 34.5
              max: 68.3
            - quality: "WEBRip-480p"
              min: 0
              preferred: 0
              max: 18
            - quality: "WEBRip-720p"
              min: 12.5
              preferred: 12.5
              max: 68.3
            - quality: "WORKPRINT"
              min: 0
              preferred: 0
              max: 18
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-remux-web-1080p
          - template: radarr-custom-formats-remux-web-1080p
        custom_formats: []
