apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
  namespace: media
  labels:
    app.kubernetes.io/name: configarr
    app.kubernetes.io/instance: configarr-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  schedule: "17 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app.kubernetes.io/name: configarr
        spec:
          restartPolicy: OnFailure
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.20.0@sha256:40180ae49ed3caab864f65682da14b172281edb19924e60a5fd357b2234cb987
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
                  readOnly: true
                - name: secrets
                  mountPath: /app/config/secrets.yml
                  subPath: secrets.yml
                  readOnly: true
                - name: repos
                  mountPath: /app/repos
          volumes:
            - name: config
              configMap:
                name: configarr
            - name: secrets
              secret:
                secretName: configarr-secrets
            - name: repos
              emptyDir: {}
