apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - config-pvcs.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - sonarr-ingress.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - radarr-ingress.yaml
  - overseerr-deployment.yaml
  - overseerr-service.yaml
  - overseerr-ingress.yaml
  - bazarr-deployment.yaml
  - bazarr-service.yaml
  - bazarr-ingress.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - prowlarr-ingress.yaml
  - gluetun-openvpn.sops.yaml
  - transmission-deployment.yaml
  - transmission-service.yaml
  - transmission-ingress.yaml
  - tautulli-deployment.yaml
  - tautulli-service.yaml
  - tautulli-ingress.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - jellyfin-ingress.yaml
