apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - default-serviceaccount.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - config-pvcs.yaml
  - configarr-configmap.yaml
  - configarr-secrets.sops.yaml
  - configarr-cronjob.yaml
  - cleanuparr-deployment.yaml
  - cleanuparr-service.yaml
  - cleanuparr-ingress.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - sonarr-ingress.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - radarr-ingress.yaml
  - overseerr-deployment.yaml
  - overseerr-service.yaml
  - overseerr-ingress.yaml
  - bazarr-deployment.yaml
  - bazarr-service.yaml
  - bazarr-ingress.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - prowlarr-ingress.yaml
  - flaresolverr-deployment.yaml
  - flaresolverr-service.yaml
  - gluetun-openvpn.sops.yaml
  - searxng-deployment.yaml
  - searxng-service.yaml
  - searxng-ingress.yaml
  - transmission-deployment.yaml
  - transmission-service.yaml
  - transmission-ingress.yaml
  - searxng-networkpolicy-openwebui.yaml
  - tautulli-deployment.yaml
  - tautulli-service.yaml
  - tautulli-ingress.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - jellyfin-ingress.yaml
  - audiobookshelf-deployment.yaml
  - audiobookshelf-service.yaml
  - audiobookshelf-ingress.yaml
  - calibre-web-deployment.yaml
  - calibre-web-service.yaml
  - calibre-web-ingress.yaml
  - calibre-web-redirects.yaml
  - immich-secrets.sops.yaml
  - immich-postgres.yaml
  - immich-redis.yaml
  - immich-machine-learning.yaml
  - immich-server.yaml
  - audiobookshelf-redirect.yaml
  - immich-redirect.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
