apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-apps
  namespace: flux-system
  labels:
    app.kubernetes.io/name: private-apps
    app.kubernetes.io/instance: private-apps-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: private-apps-auth
  url: ssh://git@github.com/romanpeters/kubernetes-private.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: private-apps
  namespace: flux-system
  labels:
    app.kubernetes.io/name: private-apps
    app.kubernetes.io/instance: private-apps-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  interval: 10m0s
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: private-apps
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 5m0s
