apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitea-redirect
  namespace: apps
spec:
  redirectRegex:
    regex: ^https?://gitea\.romanpeters\.nl/(.*)
    replacement: https://git.romanpeters.nl/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-ext
  labels:
    app.kubernetes.io/name: gitea
spec:
  ingressClassName: traefik
  rules:
    - host: git.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-redirect
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-ext
    traefik.ingress.kubernetes.io/router.middlewares: apps-gitea-redirect@kubernetescrd
  labels:
    app.kubernetes.io/name: gitea
spec:
  ingressClassName: traefik
  rules:
    - host: gitea.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  name: http
