apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.25.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 22
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: gitea-postgres:5432
            - name: DB_NAME
              value: gitea
            - name: DB_USER
              value: gitea
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: DB_PASSWORD
            - name: GITEA__database__HOST
              value: gitea-postgres:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: DB_PASSWORD
            - name: GITEA__SERVER__DOMAIN
              value: git.romanpeters.nl
            - name: GITEA__SERVER__ROOT_URL
              value: https://git.romanpeters.nl/
            - name: GITEA__SERVER__SSH_PORT
              value: "22"
            - name: GITEA__SERVER__APP_DATA_PATH
              value: /data
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
