apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  - config-pvcs.yaml
  - heimdall-deployment.yaml
  - heimdall-service.yaml
  - heimdall-ingress.yaml
  - heimdall-redirects.yaml
  - homebox-deployment.yaml
  - homebox-service.yaml
  - homebox-ingress.yaml
