apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  - config-pvcs.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - changedetection-deployment.yaml
  - changedetection-service.yaml
  - changedetection-ingress.yaml
  - heimdall-deployment.yaml
  - heimdall-service.yaml
  - heimdall-ingress.yaml
  - heimdall-redirects.yaml
  - playwright-chrome-deployment.yaml
  - playwright-chrome-service.yaml
  - uptime-kuma-deployment.yaml
  - uptime-kuma-service.yaml
  - uptime-kuma-ingress.yaml
