apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: infrastructure
data:
  settings.yaml: |
    title: Roman Peters
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Media:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 3
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
  bookmarks.yaml: |
    []
  services.yaml: |
    - Media:
        - Jellyfin:
            href: https://jellyfin.romanpeters.nl
            icon: jellyfin
        - Overseerr:
            href: https://overseerr.romanpeters.nl
            icon: overseerr
        - Sonarr:
            href: https://sonarr.romanpeters.nl
            icon: sonarr
        - Radarr:
            href: https://radarr.romanpeters.nl
            icon: radarr
        - Bazarr:
            href: https://bazarr.romanpeters.nl
            icon: bazarr
        - Prowlarr:
            href: https://prowlarr.romanpeters.nl
            icon: prowlarr
        - Transmission:
            href: https://transmission.romanpeters.nl
            icon: transmission
        - Tautulli:
            href: https://tautulli.romanpeters.nl
            icon: tautulli
    - Infrastructure:
        - Authentik:
            href: https://authentik.romanpeters.nl
            icon: mdi-shield-account
        - NGINX:
            href: https://nginx.romanpeters.nl
            icon: mdi-server
        - Proxmox:
            href: https://proxmox.romanpeters.nl
            icon: mdi-server-network
        - UniFi:
            href: https://unifi.romanpeters.nl
            icon: mdi-wifi
