apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: infrastructure
data:
  settings.yaml: |
    title: Roman Peters
    theme: dark
    color: slate
    headerStyle: boxed
    statusStyle: dot
    layout:
      Media:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 3
  widgets.yaml: |
    []
  bookmarks.yaml: |
    []
  services.yaml: |
    - Media:
        - Jellyfin:
            href: https://jellyfin.romanpeters.nl
            icon: jellyfin
            siteMonitor: https://jellyfin.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Overseerr:
            href: https://overseerr.romanpeters.nl
            icon: overseerr
            siteMonitor: https://overseerr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Sonarr:
            href: https://sonarr.romanpeters.nl
            icon: sonarr
            siteMonitor: https://sonarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Radarr:
            href: https://radarr.romanpeters.nl
            icon: radarr
            siteMonitor: https://radarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Bazarr:
            href: https://bazarr.romanpeters.nl
            icon: bazarr
            siteMonitor: https://bazarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Prowlarr:
            href: https://prowlarr.romanpeters.nl
            icon: prowlarr
            siteMonitor: https://prowlarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Transmission:
            href: https://transmission.romanpeters.nl
            icon: transmission
            siteMonitor: https://transmission.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Tautulli:
            href: https://tautulli.romanpeters.nl
            icon: tautulli
            siteMonitor: https://tautulli.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
    - Infrastructure:
        - Authentik:
            href: https://authentik.romanpeters.nl
            icon: mdi-shield-account
            siteMonitor: https://authentik.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - NGINX:
            href: https://nginx.romanpeters.nl
            icon: mdi-server
            siteMonitor: https://nginx.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Proxmox:
            href: https://proxmox.romanpeters.nl
            icon: mdi-server-network
            siteMonitor: https://proxmox.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - UniFi:
            href: https://unifi.romanpeters.nl
            icon: mdi-wifi
            siteMonitor: https://unifi.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
