apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - namespace.yaml
  - homepage-config.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml
  - homepage-ingress.yaml
