apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-http
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: media-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: overseerr.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overseerr
                port:
                  name: http
    - host: requests.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: overseerr
                port:
                  name: http
