apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app.kubernetes.io/name: overseerr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: overseerr
  ports:
    - name: http
      port: 5055
      targetPort: http
