apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - namespace.yaml
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - awx.yaml
  - resourcequota.yaml
  - limitrange.yaml
patches:
  - target:
      kind: Namespace
      name: awx
    path: awx-operator-namespace-delete.yaml
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1
