apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gen-ai
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - openwebui-mcp.sops.yaml
  - openwebui-bootstrap-config.yaml
  - default-serviceaccount.yaml
  - openwebui-pvc.yaml
  - openwebui-deployment.yaml
  - openwebui-service.yaml
  - openwebui-ingress.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
