apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config
  labels:
    app.kubernetes.io/name: n8n-config
    app.kubernetes.io/instance: n8n-config-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-ef3a4373-56f1-4ab4-8d07-36a6e41b1de3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  labels:
    app.kubernetes.io/name: heimdall-config
    app.kubernetes.io/instance: heimdall-config-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-587df120-9571-4b87-a4f7-b249b755d7b7
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  labels:
    app.kubernetes.io/name: homebox-data
    app.kubernetes.io/instance: homebox-data-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pvc-95b4b90d-557c-4feb-a0f8-6234402ac0f6
  resources:
    requests:
      storage: 5Gi
