apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  namespace: general
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
spec:
  ingressClassName: traefik
  rules:
    - host: hello.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heimdall
                port:
                  name: http
