apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: general
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - default-serviceaccount.yaml
  - config-pvcs.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - heimdall-deployment.yaml
  - heimdall-service.yaml
  - heimdall-ingress.yaml
  - heimdall-redirects.yaml
  - homebox-deployment.yaml
  - homebox-service.yaml
  - homebox-ingress.yaml
  - gitea-postgres-data-pvc.yaml
  - gitea-postgres.yaml
  - gitea-data-pvc.yaml
  - gitea-deployment.yaml
  - gitea-service.yaml
  - gitea-ingress.yaml
  - gitea-ssh-ingressroute.yaml
  - gitea-secrets.sops.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
