apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost-romanpeters-nl
  namespace: infrastructure
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-ext
spec:
  ingressClassName: traefik
  tls:
    - secretName: romanpeters-nl-tls
      hosts:
        - "*.romanpeters.nl"
  rules:
    - host: "*.romanpeters.nl"
      http:
        paths:
          - path: /outpost.goauthentik.io/
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-traefik-outpost
                port:
                  number: 9000
