apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-webui
  namespace: infrastructure
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-lan-allow-10-8@kubernetescrd
  labels:
    app.kubernetes.io/name: garage-webui
    app.kubernetes.io/instance: garage-webui-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: internal
spec:
  ingressClassName: traefik
  rules:
    - host: garage.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-webui
                port:
                  name: http
