apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage-webui
  namespace: infrastructure
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int
spec:
  ingressClassName: traefik
  rules:
    - host: garage.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage-webui
                port:
                  name: http
