apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: infrastructure
  annotations:
    external-dns: external
    traefik.ingress.kubernetes.io/router.entrypoints: websecure-int,websecure-pub
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: homepage-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  ingressClassName: traefik
  tls:
    - secretName: romanpeters-nl-tls
      hosts:
        - homepage.romanpeters.nl
  rules:
    - host: homepage.romanpeters.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  name: http
