apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-tv
  labels:
    app.kubernetes.io/name: homepage-tv
    app.kubernetes.io/instance: homepage-tv-prod
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: flux
    exposure: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage-tv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage-tv
    spec:
      initContainers:
        - name: seed-config
          image: alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /app/config
              cp -a /config-ro/. /app/config/
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: config-ro
              mountPath: /config-ro
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.10.1@sha256:0b596092c0b55fe4c65379a428a3fe90bd192f10d1b07d189a34fe5fabe7eedb
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Amsterdam"
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "tv.romanpeters.nl,rtv.romanpeters.nl,romantv.romanpeters.nl"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          emptyDir: {}
        - name: config-ro
          configMap:
            name: homepage-tv-config
