apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: infrastructure
data:
  settings.yaml: |
    title: Homepage
    theme: dark
    color: slate
    headerStyle: boxed
    statusStyle: dot
    layout:
      Widgets:
        style: row
        columns: 3
        header: false
      Apps:
        style: row
        columns: 2
      Automation:
        style: row
        columns: 2
      Monitoring:
        style: row
        columns: 2
      Softwarr:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 3
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
    - unifi_console:
        url: https://unifi.romanpeters.nl
        username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
        password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
  kubernetes.yaml: |
    mode: cluster
    ingress: false
    traefik: false
    gateway: false
  bookmarks.yaml: |
    []
  services.yaml: |
    - Widgets:
        - Plex:
            href: https://plex.romanpeters.nl
            icon: plex
            siteMonitor: https://plex.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
            widget:
              type: plex
              url: https://plex.romanpeters.nl
              key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
        - Transmission:
            href: https://transmission.romanpeters.nl
            icon: transmission
            siteMonitor: https://transmission.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
            widget:
              type: transmission
              url: https://transmission.romanpeters.nl
              rpcUrl: /transmission/
        - Uptime Kuma:
            href: https://uptime.romanpeters.nl
            icon: uptime-kuma
            siteMonitor: https://uptime.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
            widget:
              type: uptimekuma
              url: https://uptime.romanpeters.nl
              slug: rtv
        - Authentik:
            href: https://auth.romanpeters.nl
            icon: authentik
            siteMonitor: https://auth.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
            widget:
              type: authentik
              url: https://auth.romanpeters.nl
              key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"
              version: 2
        - Proxmox:
            href: https://proxmox.romanpeters.nl
            icon: proxmox
            siteMonitor: https://proxmox.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
            widget:
              type: proxmox
              url: https://proxmox.romanpeters.nl
              username: api@pam!homepage
              password: "{{HOMEPAGE_VAR_PROXMOX_API_SECRET}}"
    - Apps:
        - Audiobookshelf:
            href: https://books.romanpeters.nl
            icon: audiobookshelf
            siteMonitor: https://books.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Homebox:
            href: https://homebox.romanpeters.nl
            icon: homebox
            siteMonitor: https://homebox.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Gitea:
            href: https://git.romanpeters.nl
            icon: gitea
            siteMonitor: https://git.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Jellyfin:
            href: https://jellyfin.romanpeters.nl
            icon: jellyfin
            siteMonitor: https://jellyfin.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Calibre Web:
            href: https://ebooks.romanpeters.nl
            icon: calibre-web
            siteMonitor: https://ebooks.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Immich:
            href: https://photos.romanpeters.nl
            icon: immich
            siteMonitor: https://photos.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
    - Automation:
        - Home Assistant:
            href: https://home.romanpeters.nl
            icon: home-assistant
            siteMonitor: https://home.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - AWX:
            href: https://awx.romanpeters.nl
            icon: ansible
            siteMonitor: https://awx.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - n8n:
            href: https://n8n.romanpeters.nl
            icon: n8n
            siteMonitor: https://n8n.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
    - Monitoring:
        - Grafana:
            href: https://dashboard.romanpeters.nl
            icon: grafana
            siteMonitor: https://dashboard.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - ntfy:
            href: https://ntfy.romanpeters.nl
            icon: ntfy
            siteMonitor: https://ntfy.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - ChangeDetection:
            href: https://change.romanpeters.nl
            icon: changedetection
            siteMonitor: https://change.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Alerts:
            href: https://alerts.romanpeters.nl
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/alertmanager.svg
            siteMonitor: https://alerts.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Tautulli:
            href: https://tautulli.romanpeters.nl
            icon: tautulli
            siteMonitor: https://tautulli.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308, 401, 403]
    - Softwarr:
        - Overseerr:
            href: https://request.romanpeters.nl
            icon: overseerr
            siteMonitor: https://request.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Sonarr:
            href: https://sonarr.romanpeters.nl
            icon: sonarr
            siteMonitor: https://sonarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Radarr:
            href: https://radarr.romanpeters.nl
            icon: radarr
            siteMonitor: https://radarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Bazarr:
            href: https://bazarr.romanpeters.nl
            icon: bazarr
            siteMonitor: https://bazarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Prowlarr:
            href: https://prowlarr.romanpeters.nl
            icon: prowlarr
            siteMonitor: https://prowlarr.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
    - Infrastructure:
        - Traefik:
            href: https://traefik.romanpeters.nl
            icon: traefik
            siteMonitor: https://traefik.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - UniFi:
            href: https://unifi.romanpeters.nl
            icon: unifi
            siteMonitor: https://unifi.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - TV:
            href: https://tv.romanpeters.nl
            icon: https://images.romanpeters.nl/rtvlogo.jpeg
            siteMonitor: https://tv.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Garage:
            href: https://garage.romanpeters.nl
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/garage.svg
            siteMonitor: https://garage.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - KVM:
            href: https://kvm.romanpeters.nl
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/sipeed.svg
            siteMonitor: https://kvm.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
