apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-tv-config
  namespace: infrastructure
data:
  settings.yaml: |
    title: RomanTV
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      TV:
        style: row
        columns: 2
  widgets.yaml: |
    []
  bookmarks.yaml: |
    []
  services.yaml: |
    - TV:
        - RomanTV:
            href: https://app.plex.tv/desktop/#!/
            icon: plex
        - Request:
            href: https://request.romanpeters.nl
            icon: overseerr
        - Audiobookshelf:
            href: https://books.romanpeters.nl
            icon: mdi-book-open-page-variant
            siteMonitor: https://books.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
        - Calibre Web:
            href: https://ebooks.romanpeters.nl
            icon: mdi-book-open-variant
            siteMonitor: https://ebooks.romanpeters.nl
            siteMonitorExpectedCodes: [200, 301, 302, 303, 307, 308]
