apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - namespace.yaml
  - helmrepo.yaml
  - authentik-secrets.sops.yaml
  - helmrelease.yaml
  - homepage-config.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml
  - homepage-ingress.yaml
  - homepage-tv-config.yaml
  - homepage-tv-deployment.yaml
  - homepage-tv-service.yaml
  - homepage-tv-ingress.yaml
  - homepage-tv-redirects.yaml
