apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - namespace.yaml
  - dockerhub-read.sops.yaml
  - default-serviceaccount.yaml
  - helmrepo.yaml
  - authentik-secrets.sops.yaml
  - authentik-forward-auth-middleware.yaml
  - lan-allow-10-8-middleware.yaml
  - helmrelease.yaml
  - garage-config.yaml
  - garage-secrets.sops.yaml
  - garage-pvc.yaml
  - garage-deployment.yaml
  - garage-service.yaml
  - garage-ingress.yaml
  - garage-web-ingress.yaml
  - garage-webui-deployment.yaml
  - garage-webui-service.yaml
  - garage-webui-ingress.yaml
  - homepage-config.yaml
  - homepage-secrets.sops.yaml
  - homepage-rbac.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml
  - homepage-ingress.yaml
  - authentik-outpost-homepage-ingress.yaml
  - homepage-tv-config.yaml
  - homepage-tv-deployment.yaml
  - homepage-tv-service.yaml
  - homepage-tv-ingress.yaml
  - homepage-tv-redirects.yaml
  - traefik-external-services.yaml
  - traefik-external-ingressroutes.yaml
  - traefik-proxmox-transport.yaml
  - romanpeters-wildcard-cert.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy.yaml
